[package]
name = "openmc"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.2", features = ["dynamic_linking"] }
noisy_bevy = { version = "0.7.0" }
rand = { version = "0.8.0" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3